{
  "stderr": "",
  "stdout": "::debug::starting to run should fail\n::error title=should fail,file=tests/example.mjs,line=5,col=3::[Error [ERR_TEST_FAILURE]: false == true] {%0A  failureType: 'testCodeFailure',%0A  cause: AssertionError [ERR_ASSERTION]: false == true%0A      at TestContext.<anonymous> (file://CWD/tests/example.mjs:5:3)%0A      at Test.runInAsyncScope (node:async_hooks:203:9)%0A      at Test.run (node:internal/test_runner/test:631:25)%0A      at Test.start (node:internal/test_runner/test:542:17)%0A      at startSubtest (node:internal/test_runner/harness:214:17) {%0A    generatedMessage: true,%0A    code: 'ERR_ASSERTION',%0A    actual: false,%0A    expected: true,%0A    operator: '=='%0A  },%0A  code: 'ERR_TEST_FAILURE'%0A}\n::debug::starting to run should pass\n::debug::completed running should pass\n::group::Test results (1 passed, 1 failed)\n::notice::Total Tests: 2%0ASuites 📂: 0%0APassed ✅: 1%0AFailed ❌: 1%0ACanceled 🚫: 0%0ASkipped ⏭️: 0%0ATodo 📝: 0%0ADuration 🕐: *ms\n::endgroup::\n",
  "exitCode": 1
}